swagger: '2.0'
info:
  description: API methods for Culturale
  title: Culturale API
schemes:
- https
consumes:
- application/json
produces:
- application/json

paths:
  /events:
    get:
      description: Returns all events from database
      security:
        - bearerAuth: []
      responses: 
        '200': 
          description: Ok
          schema:
            type: array 
            items:
              $ref: '#/definitions/event'
        '403':
          description: Unauthorized
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /users/create:
    post:
      description: Creates a user registered in in BE
      responses: 
        '200': 
          description: Ok
          schema:
            type: object 
            properties:
              user:
                $ref: '#/definitions/user'
              message:
                type: string
        '404':
          description: Bad request
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /events/:id/messages:
    get:
      description: 'Returns all messages of an event chat'
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Ok
          schema:
            type: object 
            properties:
              messages:
                type: array
                items:
                  $ref: '#/definitions/message'
        '404':
          description: Bad request
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
definitions:
  event:
    type: object
    required:
      - id
      - codi
      - denominacio
      - url
    properties:
      id:
        type: string
      codi:
        type: integer
      denominacio:
        type: string
      dataIni:
        type: string
      dataFi:
        type: string
      horari:
        type: string
      address:
        type: string
      url:
        type: string
      participants:
        type: array
        items:
          $ref: '#/definitions/user'
      chat:
        $ref: '#/definitions/chat'
  user:
    type: object
    properties:
      name:
        type: string
      username:
        type: string
      email:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      profilePicture:
        type: string
      userType:
        type: string
  chat:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/message'
  message:
    type: object
    properties:
      content:
        type: string
      userId:
        type: string
      date:
        type: string
  error:
    type: object
    properties:
      code:
        type: integer
        format: int
      message:
        type: string
