swagger: '2.0'
info:
  description: API methods for Culturale
  title: Culturale API
schemes:
- https
consumes:
- application/json
produces:
- application/json

paths:
  /login:
    post:
      description: Logs in to Culturale API
      responses:
        '200':
          description: Ok
          schema:
            type: object
            required:
              - user
              - token
            properties:
              user:
                $ref: '#/definitions/user'
              token:
                type: string
        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /events:
    get:
      description: Returns all events from database
      security:
        - bearerAuth: []
      responses: 
        '200': 
          description: Ok
          schema:
            type: object
            properties:
              events:
                type: array 
                items:
                  $ref: '#/definitions/event'
        '403':
          description: Unauthorized
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /users:
      get:
        description: Returns all users from database
        security:
          - bearerAuth: []
        responses: 
          '200': 
            description: Ok
            schema:
              type: object
              properties:
                users:
                  type: array 
                  items:
                    $ref: '#/definitions/user'
          '403':
            description: Unauthorized
            schema:
              type: object 
              properties:
                data:
                  type: object
                error:
                  $ref: '#/definitions/error'
          '500':
            description: Internal server error
            schema:
              type: object 
              properties:
                data:
                  type: object
                error:
                  $ref: '#/definitions/error'
  /users/create:
    post:
      description: Creates a user registered in in BE
      responses: 
        '200': 
          description: Ok
          schema:
            type: object 
            properties:
              user:
                $ref: '#/definitions/user'
              message:
                type: string
        '404':
          description: Bad request
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /events/:id/messages:
    get:
      description: 'Returns all messages of an event chat'
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Ok
          schema:
            type: object 
            properties:
              messages:
                type: array
                items:
                  $ref: '#/definitions/message'
        '404':
          description: Bad request
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /users/edit:
    post:
      description: 'Returns the edited user'
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Ok
          schema:
            type: object 
            properties:
              user:
                $ref: '#/definitions/user'
              message:
                type: string
        '404':
          description: Bad request
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /events/newParticipant:
    post:
      description: 'It adds a participant into an event'
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Ok
          schema:
            type: object 
            properties:
              message:
                type: string
        '404':
          description: Bad request
          schema:
            type: object
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /events/addReview:
    post:
      description: 'It adds a review into an event'
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Ok
          schema:
            type: object 
            properties:
              review:
                $ref: '#/definitions/review'
              message:
                type: string
        '404':
          description: Bad request
          schema:
            type: object
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
                
  /users/deleteFollower:
    delete:
      description: 'Deletes de users follower'
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Ok
          schema:
            type: object
            properties:
              followers:
                type: array
                items:
                  $ref: '#/definitions/user'
              message:
                type: string
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '404':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
  /users/newFollower:
    post:
      description: 'Adds a new  follower'
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Ok
          schema:
            type: object
            properties:
              followers:
                type: array
                items:
                  $ref: '#/definitions/user'
              message:
                type: string
        '500':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'
        '404':
          description: Internal server error
          schema:
            type: object 
            properties:
              data:
                type: object
              error:
                $ref: '#/definitions/error'

definitions:
  event:
    type: object
    required:
      - _id
      - codi
      - denominacio
      - url
      - descripcio
      - horari
      - adress
      - dataIni
      - dataFi
      - lat
      - long
      - photo
    properties:
      _id:
        type: string
      codi:
        type: integer
      denominacio:
        type: string
      descripcio:
        type: string
      dataIni:
        type: string
      dataFi:
        type: string
      horari:
        type: string
      adress:
        type: string
      url:
        type: string
      lat:
        type: number
      long:
        type: number
      photo:
        type: string
      participants:
        type: array
        items:
          $ref: '#/definitions/user'
      chat:
        $ref: '#/definitions/chat'
  user:
    type: object
    required:
      - name
      - _id
      - username
      - email
      - phoneNumber
      - profilePicture
      - usertype
    properties:
      _id:
        type: string
      name:
        type: string
      username:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      profilePicture:
        type: string
      usertype:
        type: string
      followers:
        type: array
        items:
          $ref: '#/definitions/user'
      followeds:
        type: array
        items:
          $ref: '#/definitions/user'
      eventSub:
        type: array
        items:
          $ref: '#/definitions/event'
  chat:
    type: object
    required:
      - _id
      - messages
    properties:
      _id:
        type: string
      messages:
        type: array
        items:
          $ref: '#/definitions/message'
  message:
    type: object
    required:
      - content
      - userId
      - date
    properties:
      _id:
        type: string
      content:
        type: string
      userId:
        type: string
      date:
        type: string
  error:
    type: object
    properties:
      code:
        type: integer
        format: int
      message:
        type: string
  review:
    type: object
    required:
      - puntuation
      - authorId
      - eventId
    properties:
      puntuation:
        type: number
      comment:
        type: string
      authorId:
        type: string
      eventId:
        type: string
    
