/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/events': {
    /** Returns all events from database */
    get: {
      responses: {
        /** Ok */
        200: {
          schema: definitions['event'][];
        };
        /** Unauthorized */
        403: {
          schema: {
            data?: { [key: string]: unknown };
            error?: definitions['error'];
          };
        };
        /** Internal server error */
        500: {
          schema: {
            data?: { [key: string]: unknown };
            error?: definitions['error'];
          };
        };
      };
    };
  };
}

export interface definitions {
  event: {
    id: string;
    codi: number;
    denominacio: string;
    dataIni?: string;
    dataFi?: string;
    horari?: string;
    address?: string;
    url: string;
    participants?: definitions['user'][];
    chat?: definitions['chat'];
  };
  user: {
    name?: string;
    username?: string;
    email?: string;
    password?: string;
    phoneNumber?: string;
    profilePicture?: string;
    userType?: string;
  };
  chat: {
    messages?: definitions['message'][];
  };
  message: {
    content?: string;
    userId?: string;
    date?: string;
  };
  error: {
    /** Format: int */
    code?: number;
    message?: string;
  };
}

export interface operations {}

export interface external {}
